### ISSUE TITLE
on 2020.11.14 task

### ISSUE THREAD

**Issue by agricolamz** [snchknn/botlikh-mp-2020#1]
* *-ɬi* forms (like in 13, 42) are not implemented
* *-čʼuku* forms (like in 207, 3090) are not implemented
* Don't try to gloss. The main goal of analyzer is to provide an initial stem.
* I'm against the `0` and `00` glosses. I want them to be allomorphs of the stems 100 and 1000.
* Add POS tag `<num>`

**Comment by nlhowell** [comment]
> Don't try to gloss. The main goal of analyzer is to provide an
> initial stem.

> I'm against the `0` and `00` glosses. I want them to be allomorphs
of the stems 100 and 1000.

These issues are still present in the new lexd source. (BTW, please
get rid of the old one if you don't intend to continue it; git keeps
track of the versions, you don't need to keep multiple copies around.)

As @agricolamz mentioned, please just lemmatise (keeping the Botlikh
lemma) and tag (e.g. `<num>`), and have these "multiplier" morphemes
be allomorphs of the Botlikh words for 100 and 1000.

**Comment by nlhowell** [comment]
Seems to me:

> *-ɬi* forms (like in 13, 42) are not implemented
> *-čʼuku* forms (like in 207, 3090) are not implemented

were addressed in commit ac4e4c598423aadd2b5d5346809befc106db6cfd

and

> Don't try to gloss. The main goal of analyzer is to provide an
> initial stem.

> I'm against the `0` and `00` glosses. I want them to be allomorphs
> of the stems 100 and 1000.

> Add POS tag `<num>`

in 3c3cfdf6b8329f7222f15bbb1037f05a549d9908 .

@agricolamz, I think we can mark this RESOLVED?

**Comment by agricolamz** [comment]
sure!
