### ISSUE TITLE
add tests with sources, in .csv format

### ISSUE THREAD

**Issue by nlhowell** [snchknn/botlikh-mp-2020#6]
see https://gitlab.com/nlhowell/abq.git for examples

**Comment by snchknn** [comment]
@nlhowell added in recent commits, please check it out

**Comment by nlhowell** [comment]
snchknn - notifications@github.com wrote:
> @nlhowell added in recent commits, please check it out

Format looks good! Running `make check` doesn't seem to work, though;
maybe you are missing some of the additions to `Makefile`? I think
specifically about the lines (from Abaza; you will have to change
`abaza.gen.hfst`):

(insert near beginning of `Makefile`)
```
tests = tests_numbers.csv
test_sources = $(shell sed -s 1d $(tests) | cut -d, -f5 | sort -u)
```

(replace the last bit of `Makefile` with these rules)
```
%.pass.txt: $(tests)
	awk -F, '$$5 == "$*" && $$4 == "pass" {print $$1 ":" $$3}' $^  | sort -u > $@
%.ignore.txt: $(tests)
	awk -F, '$$5 == "$*" && $$4 == "ignore" {print $$1 ":" $$3}' $^  | sort -u > $@
check-gen: main.gen.hfst $(foreach t,$(test_sources),$(t).pass.txt $(t).ignore.txt)
	for t in $(test_sources); do echo $$t; bash compare.sh $< $$t.ignore.txt; bash compare.sh $< $$t.pass.txt || exit $$?; done
check: check-gen
```

Does that improve it?
