### ISSUE TITLE
pass/ignore again

### ISSUE THREAD

**Issue by snchknn** [snchknn/botlikh-mp-2020#8]
@nlhowell you once mentioned that i should prefer forms that are more easily generated by my transducer (iirc), but does that make sense if i build my transducer using the same data from the same source?
should i prefer one form that fits the common morphological rule to the one that breaks it? or one that is found in sample text/examples to the one that is found in grammar description itself?

**Comment by nlhowell** [comment]
snchknn - notifications@github.com wrote:
> @nlhowell you once mentioned that i should prefer forms that are more
> easily generated by my transducer (iirc),

I'm not sure in what sense this is meant; can you remind me the
context of that conversation?

> but does that make sense if i build my transducer using the same
> data from the same source?

This is a way of providing proof that your transducer is consistent
with your source; if somebody sees some form created by your
transducer, they can go see if there are similar forms which are
attested.

> should i prefer one form that fits the common morphological rule to
> the one that breaks it? or one that is found in sample text/examples
> to the one that is found in grammar description itself?

I think you should be including as many tests as you can get your
hands on. If you have hand-analysed attested forms, all of this should
go into tests, ideally.

Does that answer your question?

Cheers,
Nick
